name: github pages # workflow名称

on: # 触发条件
  # 每当 push 到 master 分支时触发部署
  push:
    branches: [master] # default branch
    # 是否手动触发部署
    workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest #ubuntu-18.04 指定运行所需要的虚拟机环境（必填）
    steps:
      - uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: "14"

      - run: npm install
      # 文档编译命令，如果是 react 模板需要修改为 npm run docs:build
      - run: npm run docs:build
      - run: npm run docs:deploy
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 文档目录，如果是 react 模板需要修改为 docs-dist
          publish_dir: ./dist
